name: Build and Release Chrome Extension

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install

    - name: Extract tag version
      id: extract_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "Extracted version: $VERSION"

    - name: Update manifest.json version
      run: |
        # Install jq for JSON manipulation
        sudo apt-get update
        sudo apt-get install -y jq
        
        # Update version in manifest.json
        jq '.version = "${{ env.VERSION }}"' public/manifest.json > temp.json
        mv temp.json public/manifest.json
        
        # Show updated manifest
        cat public/manifest.json

    - name: Build extension
      run: |
        # Check if build command exists in package.json
        if pnpm run build --dry-run > /dev/null 2>&1; then
          pnpm run build
        else
          echo "Build command not found in package.json, copying public directory"
          mkdir -p dist
          cp -r public/* dist/
        fi

    - name: Install zip utility
      run: sudo apt-get update && sudo apt-get install -y zip

    - name: Create PEM file from secret
      run: |
        echo "${{ secrets.WEB_EXT_PRIVATE_KEY }}" > extension.pem

    - name: Prepare extension directory
      run: |
        # Wait for build directory to be created
        sleep 2
        
        # Determine which directory to use for the extension
        if [ -d "build" ]; then
          echo "Build directory found, using build/"
          EXT_DIR="build"
        else
          echo "Build directory not found, using public/"
          EXT_DIR="public"
        fi
        
        # Ensure manifest.json exists in the extension directory
        if [ ! -f "$EXT_DIR/manifest.json" ]; then
          echo "Copying manifest.json to $EXT_DIR/"
          cp public/manifest.json $EXT_DIR/
        fi
        
        # Store the directory for the next steps
        echo "EXT_DIR=$EXT_DIR" >> $GITHUB_ENV

    - name: Create ZIP package
      run: |
        # Create ZIP file from the extension directory
        cd ${{ env.EXT_DIR }}
        zip -r ../Additional-Miniplayer-${{ env.VERSION }}.zip . -x "*.DS_Store" "__MACOSX/*"
        cd ..

    - name: Install CRX creation tools
      run: |
        # Install both crx3 and crx packages for CRX creation
        pnpm install -g crx3
        pnpm install crx -g

    - name: Create CRX package with crx3
      run: |
        # Create CRX file using crx3 (primary method)
        crx3 ${{ env.EXT_DIR }} extension.pem --output Additional-Miniplayer-${{ env.VERSION }}.crx
      continue-on-error: true

    - name: Create CRX package with crx (fallback)
      if: steps.create-crx-with-crx3.outcome == 'failure'
      run: |
        # If crx3 failed, try with crx package
        crx pack ${{ env.EXT_DIR }} --private-key extension.pem --output Additional-Miniplayer-${{ env.VERSION }}.crx

    - name: Verify CRX creation
      run: |
        if [ -f "Additional-Miniplayer-${{ env.VERSION }}.crx" ]; then
          echo "CRX file created successfully"
        else
          echo "WARNING: CRX file was not created. Users can install using the ZIP file."
          echo "To install manually: Open chrome://extensions, enable Developer mode, click 'Load unpacked' and select the extracted ZIP contents."
        fi

    - name: Upload CRX to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Additional-Miniplayer-${{ env.VERSION }}.crx
        asset_name: Additional-Miniplayer-${{ env.VERSION }}.crx
        asset_content_type: application/octet-stream

    - name: Upload ZIP to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Additional-Miniplayer-${{ env.VERSION }}.zip
        asset_name: Additional-Miniplayer-${{ env.VERSION }}.zip
        asset_content_type: application/zip